/**
 * config.ts — Configurable Thresholds & Settings for Multi-Source Intelligence
 * ==============================================================================
 * Thresholds are centralized here rather than hardcoded throughout the codebase.
 */

export const SEISMIC_CONFIG = {
  // Bounding Boxes
  BOUNDS: {
    NEPAL: {
      minLat: 26.3,
      maxLat: 30.5,
      minLng: 80.0,
      maxLng: 88.3,
    },
    HIMALAYAN_REGIONAL: {
      minLat: 24.0,
      maxLat: 33.0,
      minLng: 77.0,
      maxLng: 92.0,
    },
  },

  // Event Correlation & Matching Thresholds (Section 3)
  MATCHING: {
    // Maximum time difference between reported origin times (in seconds)
    MAX_TIME_DIFF_SEC: 180, // 3 minutes window
    // Maximum geographical distance between reported epicenters (in km)
    MAX_DISTANCE_KM: 130, // Account for regional network geometry differences
    // Maximum magnitude difference before correlation requires tighter spatial/temporal match
    MAX_MAGNITUDE_DIFF: 1.6,
    // Relaxed time window if distance is very tight (< 25km)
    TIGHT_DISTANCE_KM: 25,
    EXTENDED_TIME_DIFF_SEC: 300,
  },

  // Cross-Source Agreement Thresholds (Section 7)
  AGREEMENT_THRESHOLDS: {
    HIGH: {
      minSources: 2,
      maxDistanceKm: 40,
      maxTimeDeltaSec: 30,
      maxMagDiff: 0.6,
    },
    MODERATE: {
      minSources: 2,
      maxDistanceKm: 90,
      maxTimeDeltaSec: 90,
      maxMagDiff: 1.2,
    },
    // LOW is anything with >= 2 sources exceeding MODERATE thresholds
  },

  // Cache & Polling Configuration (Section 15)
  PIPELINE: {
    CACHE_TTL_MS: 45_000, // 45 seconds server cache
    REFRESH_CADENCE_MS: 60_000, // 1 minute auto refresh
    REQUEST_TIMEOUT_MS: 9_000, // 9 seconds external timeout
    MAX_RETRIES: 2,
    BACKOFF_INITIAL_MS: 1_000,
    BACKOFF_MULTIPLIER: 2,
  },

  // Standard Educational Text (Section 9, 18, 19)
  EXPLAINERS: {
    WHY_VALUES_DIFFER: [
      "Seismic station networks: NEMRC uses local Nepal broadband & short-period stations; CENC uses Chinese & Tibetan regional networks; USGS uses the Global Seismographic Network (GSN).",
      "Velocity models: Different agencies use distinct 1D or 3D crustal velocity models for seismic wave propagation in the Himalayan collision zone.",
      "Magnitude scales: Local magnitude (ML), surface wave magnitude (Ms), body wave magnitude (mb), and moment magnitude (Mw) measure distinct wave frequencies and do not scale identically.",
      "Epicenter calculation: Near-source vs. teleseismic station ray-paths can introduce spatial centroid offsets of 5–30 km.",
    ],
    STANDARD_DISCLAIMER:
      "The Multi-Source Assessment is generated by this application for transparent cross-verification and does not replace official values reported by individual agencies (NEMRC, CEA/CENC, USGS).",
  },
};
