/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestYourselfRouteImport } from './routes/test-yourself'
import { Route as PreparednessRouteImport } from './routes/preparedness'
import { Route as HistoricalRouteImport } from './routes/historical'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TestYourselfRoute = TestYourselfRouteImport.update({
  id: '/test-yourself',
  path: '/test-yourself',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparednessRoute = PreparednessRouteImport.update({
  id: '/preparedness',
  path: '/preparedness',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRoute = HistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/historical': typeof HistoricalRoute
  '/preparedness': typeof PreparednessRoute
  '/test-yourself': typeof TestYourselfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/historical': typeof HistoricalRoute
  '/preparedness': typeof PreparednessRoute
  '/test-yourself': typeof TestYourselfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/historical': typeof HistoricalRoute
  '/preparedness': typeof PreparednessRoute
  '/test-yourself': typeof TestYourselfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/historical' | '/preparedness' | '/test-yourself'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/historical' | '/preparedness' | '/test-yourself'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/historical'
    | '/preparedness'
    | '/test-yourself'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoricalRoute: typeof HistoricalRoute
  PreparednessRoute: typeof PreparednessRoute
  TestYourselfRoute: typeof TestYourselfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-yourself': {
      id: '/test-yourself'
      path: '/test-yourself'
      fullPath: '/test-yourself'
      preLoaderRoute: typeof TestYourselfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparedness': {
      id: '/preparedness'
      path: '/preparedness'
      fullPath: '/preparedness'
      preLoaderRoute: typeof PreparednessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical': {
      id: '/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof HistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoricalRoute: HistoricalRoute,
  PreparednessRoute: PreparednessRoute,
  TestYourselfRoute: TestYourselfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
