/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafeZonesRouteImport } from './routes/safe-zones'
import { Route as PreparednessRouteImport } from './routes/preparedness'
import { Route as HistoricalRouteImport } from './routes/historical'
import { Route as GisRouteImport } from './routes/gis'
import { Route as DamageAssessmentRouteImport } from './routes/damage-assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SafeZonesRoute = SafeZonesRouteImport.update({
  id: '/safe-zones',
  path: '/safe-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparednessRoute = PreparednessRouteImport.update({
  id: '/preparedness',
  path: '/preparedness',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRoute = HistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageAssessmentRoute = DamageAssessmentRouteImport.update({
  id: '/damage-assessment',
  path: '/damage-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/damage-assessment': typeof DamageAssessmentRoute
  '/gis': typeof GisRoute
  '/historical': typeof HistoricalRoute
  '/preparedness': typeof PreparednessRoute
  '/safe-zones': typeof SafeZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/damage-assessment': typeof DamageAssessmentRoute
  '/gis': typeof GisRoute
  '/historical': typeof HistoricalRoute
  '/preparedness': typeof PreparednessRoute
  '/safe-zones': typeof SafeZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/damage-assessment': typeof DamageAssessmentRoute
  '/gis': typeof GisRoute
  '/historical': typeof HistoricalRoute
  '/preparedness': typeof PreparednessRoute
  '/safe-zones': typeof SafeZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/damage-assessment'
    | '/gis'
    | '/historical'
    | '/preparedness'
    | '/safe-zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/damage-assessment'
    | '/gis'
    | '/historical'
    | '/preparedness'
    | '/safe-zones'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/damage-assessment'
    | '/gis'
    | '/historical'
    | '/preparedness'
    | '/safe-zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DamageAssessmentRoute: typeof DamageAssessmentRoute
  GisRoute: typeof GisRoute
  HistoricalRoute: typeof HistoricalRoute
  PreparednessRoute: typeof PreparednessRoute
  SafeZonesRoute: typeof SafeZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safe-zones': {
      id: '/safe-zones'
      path: '/safe-zones'
      fullPath: '/safe-zones'
      preLoaderRoute: typeof SafeZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparedness': {
      id: '/preparedness'
      path: '/preparedness'
      fullPath: '/preparedness'
      preLoaderRoute: typeof PreparednessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical': {
      id: '/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof HistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-assessment': {
      id: '/damage-assessment'
      path: '/damage-assessment'
      fullPath: '/damage-assessment'
      preLoaderRoute: typeof DamageAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DamageAssessmentRoute: DamageAssessmentRoute,
  GisRoute: GisRoute,
  HistoricalRoute: HistoricalRoute,
  PreparednessRoute: PreparednessRoute,
  SafeZonesRoute: SafeZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
